### ISSUE TITLE
Website doesn't work properly over HTTPS

### ISSUE THREAD

**Issue by rsp** [neurokernel/neurokernel.github.io#1]
The website doesn't work properly when accessed over HTTPS: https://neurokernel.github.io/

The video doesn't load at all and several errors about insecure content are displayed in the console and also [the shield icon](https://support.google.com/chrome/answer/1342714?hl=en) in Chrome is displayed ![Shield](https://lh5.ggpht.com/GaF5ZPlgk5wUvrtmzPYlqPtMml33ZJH3bnxG6dKbZRJ_FT0bAZWo2MFKmvZIbwpa_jevXFwW=w19) with a message: "This page is trying to load scripts from unauthenticated sources"

![kernel-screen-01-500](https://cloud.githubusercontent.com/assets/119231/7135946/089a879c-e2ac-11e4-922a-098f6a24af76.png)

**Comment by rsp** [comment]
This should be fixed by the pull request #2

**Comment by lebedov** [comment]
Thanks, Rafał!
